# Generated by Django 3.2.21 on 2023-10-03 10:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.ManyToManyField(blank=True, to='hill.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='CottageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hill.cottage')),
            ],
        ),
    ]
