# Generated by Django 3.2.21 on 2023-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0002_amenities_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='things_to_know',
            field=models.TextField(blank=True, null=True),
        ),
    ]
