# Generated by Django 3.2.21 on 2023-10-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0004_auto_20231009_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='things_to_know',
        ),
    ]
