# Generated by Django 3.2.21 on 2023-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0005_remove_cottage_things_to_know'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingsToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cottage',
            name='things_to_know',
            field=models.ManyToManyField(blank=True, null=True, to='hill.ThingsToKnow'),
        ),
    ]
