# Generated by Django 3.2.21 on 2023-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0007_alter_cottage_things_to_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingstoknow',
            name='category',
            field=models.CharField(choices=[('Checking in and out', 'Checking in and out'), ('During your stay', 'During your stay'), ('Additional Rules', 'Additional Rules'), ('Before you leave', 'Before you leave')], default='', max_length=50),
        ),
    ]
