# Generated by Django 3.2.21 on 2023-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0009_amenities_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='no_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cottage',
            name='no_of_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
