# Generated by Django 3.2.21 on 2023-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0011_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
