# Generated by Django 3.2.21 on 2023-10-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
