# Generated by Django 3.2.21 on 2023-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0019_thingstodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='category',
            field=models.CharField(choices=[('Bathroom', 'Bathroom'), ('Bedroom and Laundry', 'Bedroom and Laundry'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Heating and Cooling', 'Heating and Cooling'), ('Home Saftey', 'Home Saftey'), ('Internet', 'Internet'), ('Kitchen and Dining', 'Kitchen and Dining'), ('Property Features', 'Property Features'), ('Parking', 'Parking'), ('Services', 'Services'), ('Not Included', 'Not Included')], default='', max_length=50),
        ),
    ]
