# Generated by Django 3.2.21 on 2023-10-19 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0020_alter_amenities_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
