# Generated by Django 3.2.21 on 2023-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hill', '0021_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
